# Generated by Django 5.2.6 on 2025-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
